import form.formmhs;
import form.frmmhs;
import java.awt.Component;
import java.awt.Dimension;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bagus Perdana
 */
public class frameutama extends javax.swing.JFrame {

    public static class UIbaru extends Component
    {
        //konstruktor
        public UIbaru()
        {
            
        }        
    }
    /**
     * Creates new form frameutama
     */
    public frameutama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        panelutama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menulaporan = new javax.swing.JMenu();
        menumhs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menudosen = new javax.swing.JMenuItem();
        menuus = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        menufile.setText("File");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Keluar");
        menufile.add(jMenuItem8);

        jMenuBar1.add(menufile);

        menulaporan.setText("Laporan");

        menumhs.setText("Data Mahasiswa");
        menumhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumhsActionPerformed(evt);
            }
        });
        menulaporan.add(menumhs);
        menulaporan.add(jSeparator1);

        menudosen.setText("Data Dosen");
        menudosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudosenActionPerformed(evt);
            }
        });
        menulaporan.add(menudosen);

        jMenuBar1.add(menulaporan);

        menuus.setText("About US");
        jMenuBar1.add(menuus);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menumhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumhsActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        frmmhs mhs = new frmmhs();
        
        //ambil sizescreen
        Dimension layarutama = this.getSize();
        Dimension layarmhs = mhs.getSize();
        
        //simpan posisi frame mahasiswa ditengah
        mhs.setLocation(layarutama.width/2-layarmhs.width/2,layarutama.height/2-layarmhs.height/2);
        
        panelutama.add(mhs);
        mhs.setVisible(true);
        
    }//GEN-LAST:event_menumhsActionPerformed

    private void menudosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudosenActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        
        formmhs dosen = new formmhs();
        dosen.setVisible(true);
        panelutama.add(dosen);
    }//GEN-LAST:event_menudosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new UIbaru());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error, Karena"+e);
        
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menudosen;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenu menulaporan;
    private javax.swing.JMenuItem menumhs;
    private javax.swing.JMenu menuus;
    private javax.swing.JDesktopPane panelutama;
    // End of variables declaration//GEN-END:variables
}